name: clever_stepper
description: Modified version of Stepper from material library for additional features.
version: 0.1.4
homepage: https://github.com/cleverflow/clever_stepper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
